# Configuration file for webgen
# Used to set the parameters of the plugins
FileCopyHandler:
  paths: 
    - "**/*.css"
    - "**/*.jpg"
    - "**/*.png"
    - "**/*.gif"
    - "**/*.js"
    - "**/*.html"
    - "**/*.rb"

